version: '3'
services:
  web:
    image: py-server
    deploy:
      replicas: 4
    ports:
      - 8080:8080
    networks:
      - my_network
    depends_on:
      - "mongo"
  mongo:
      image: "mongo" 
      ports:
       - 27017:27017
      networks:
        - my_network
      volumes:
      - my_db:/data/db

networks:
    my_network:

volumes:
  my_db:
